jobs:
  ci:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./test/check

name: Run

on:
  schedule:
    - cron: "50 2/3 * * *"
